apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- apigee-route.yaml

patches:
- target:
    group: apigee.cloud.google.com
    version: v1alpha1
    kind: ApigeeRouteConfig
  patch: |-
    - op: add
      path: /spec/additionalGateways
      value: ["custom-additional-route"]
