# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apigee.cloud.google.com/v1alpha2
kind: ApigeeOrganization
metadata:
  name: org
spec:
  components:
    cassandraUserSetup:
      podServiceAccountName: "apigee-cassandra-user-setup-svc-account-${ORGANIZATION_NAME}" # kpt-set: apigee-cassandra-user-setup-svc-account-${ORGANIZATION_NAME}
    cassandraSchemaSetup:
      podServiceAccountName: "apigee-cassandra-schema-setup-svc-account-${ORGANIZATION_NAME}" # kpt-set: apigee-cassandra-schema-setup-svc-account-${ORGANIZATION_NAME}
    connectAgent:
      podServiceAccountName: "apigee-connect-agent-svc-account-${ORGANIZATION_NAME}" # kpt-set: apigee-connect-agent-svc-account-${ORGANIZATION_NAME}
    watcher:
      podServiceAccountName: "apigee-watcher-svc-account-${ORGANIZATION_NAME}" # kpt-set: apigee-watcher-svc-account-${ORGANIZATION_NAME}
    mart:
      podServiceAccountName: "apigee-mart-svc-account-${ORGANIZATION_NAME}" # kpt-set: apigee-mart-svc-account-${ORGANIZATION_NAME}
    udca:
      podServiceAccountName: "apigee-udca-svc-account-${ORGANIZATION_NAME}" # kpt-set: apigee-udca-svc-account-${ORGANIZATION_NAME}