apiVersion: apigee.cloud.google.com/v1alpha2
kind: ApigeeOrganization
metadata:
  name: org
spec:
  components:
    cassandraUserSetup:
      podServiceAccountName: "apigee-cassandra-user-setup-svc-account-${ORGANIZATION_NAME}" # kpt-set: apigee-cassandra-user-setup-svc-account-${ORGANIZATION_NAME}
    cassandraSchemaSetup:
      podServiceAccountName: "apigee-cassandra-schema-setup-svc-account-${ORGANIZATION_NAME}" # kpt-set: apigee-cassandra-schema-setup-svc-account-${ORGANIZATION_NAME}
    connectAgent:
      podServiceAccountName: "apigee-connect-agent-svc-account-${ORGANIZATION_NAME}" # kpt-set: apigee-connect-agent-svc-account-${ORGANIZATION_NAME}
    watcher:
      podServiceAccountName: "apigee-watcher-svc-account-${ORGANIZATION_NAME}" # kpt-set: apigee-watcher-svc-account-${ORGANIZATION_NAME}
    mart:
      podServiceAccountName: "apigee-mart-svc-account-${ORGANIZATION_NAME}" # kpt-set: apigee-mart-svc-account-${ORGANIZATION_NAME}
    udca:
      podServiceAccountName: "apigee-udca-svc-account-${ORGANIZATION_NAME}" # kpt-set: apigee-udca-svc-account-${ORGANIZATION_NAME}