# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Service
metadata:
  labels:
    app: apigee-istiod
    apigee.cloud.google.com/platform: apigee
  name: apigee-ingressgateway-manager
  namespace: "apigee"
spec:
  ports:
  - name: grpc-xds
    port: 15010
    protocol: TCP
    targetPort: 15010
  - name: https-dns
    port: 15012
    protocol: TCP
    targetPort: 15012
  - name: https-webhook
    port: 443
    protocol: TCP
    targetPort: 15017
  - name: http-monitoring
    port: 15014
    protocol: TCP
    targetPort: 15014
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 15053
  - name: dns-tls
    port: 853
    protocol: TCP
    targetPort: 15053
  selector:
    app: apigee-istiod
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apigee-istiod
    apigee.cloud.google.com/platform: apigee
  name: apigee-ingressgateway-manager
  namespace: "apigee"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apigee-istiod
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        apigee.cloud.google.com/platform: apigee
        app: apigee-istiod
    spec:
      containers:
      - args:
        - discovery
        - --monitoringAddr=:15014
        - --log_output_level=default:debug
        - --log_output_level=debug
        - --domain
        - cluster.local
        - --keepaliveMaxServerConnectionAge
        - 30m
        - --tlsCertFile=/istiod-cert/tls.crt
        - --tlsKeyFile=/istiod-cert/tls.key
        - --caCertFile=/istiod-cert/ca.crt
        - --configDir=/var/lib/istio/configurations
        env:
        - name: REVISION
          value: default
        - name: JWT_POLICY
          value: third-party-jwt
        - name: PILOT_CERT_PROVIDER
          value: custom
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.serviceAccountName
        - name: PILOT_TRACE_SAMPLING
          value: "1"
        - name: PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_OUTBOUND
          value: "false"
        - name: PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_INBOUND
          value: "false"
        - name: INJECTION_WEBHOOK_CONFIG_NAME
          value: istio-sidecar-injector
        - name: ISTIOD_ADDR
          value: apigee-ingressgateway-manager.apigee.svc:15012
        - name: PILOT_ENABLE_ANALYSIS
          value: "false"
        - name: CLUSTER_ID
          value: kubernetes
        - name: XDS_AUTH
          value: "true"
        image: gcr.io/apigee-release/hybrid/apigee-asm-istiod:1.12.6-asm.2
        imagePullPolicy: IfNotPresent
        name: discovery
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 15010
          protocol: TCP
        - containerPort: 15017
          protocol: TCP
        - containerPort: 15053
          protocol: TCP
        - containerPort: 15012
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 512Mi
        securityContext:
          capabilities:
            drop:
            - ALL
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/istio/config
          name: config-volume
        - mountPath: /var/run/secrets/tokens
          name: istio-token
          readOnly: true
        - mountPath: /var/run/secrets/istio-dns
          name: local-certs
        - mountPath: /etc/cacerts
          name: cacerts
          readOnly: true
        - mountPath: /var/lib/istio/inject
          name: inject
          readOnly: true
        - mountPath: "/var/lib/istio/configurations"
          name: istiod-config
          readOnly: true
        - mountPath: "/istiod-cert"
          name: apigee-istiod-cert
          readOnly: true
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election=false
        - --apigee-runtime-type=hybrid
        - --log-level=debug
        - --enable-webhooks=false
        - --enable-controllers=true
        - --disable-apigee-environment-controller=true
        - --disable-apigee-organization-controller=true
        - --disable-apigee-datastore-controller=true
        - --disable-apigee-deployment-controller=true
        - --disable-apigee-telemetry-controller=true
        - --disable-apigee-redis-controller=true
        - --disable-cassandra-data-replication-controller=true
        - --disable-apigee-route-controller=true
        - --disable-apigee-deployment-controller=true
        - --metrics-addr=0
        - --istio-config-dir=/var/lib/istio/configurations
        - --apigee-service-name=production
        - --enable-api-client=true
        - --disable-istio-config-in-apiserver=true
        - --disable-remove-old-version-crd-status=true
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command:
        - /manager
        image: gcr.io/apigee-release/hybrid/apigee-operators:1.8.1
        imagePullPolicy: Always
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        - containerPort: 8081
          name: healthcheck
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /readyz
            port: healthcheck
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
        - mountPath: "/var/lib/istio/configurations"
          name: istiod-config
        - mountPath: "/envoyfilter"
          name: envoyfilter
          readOnly: true
        - mountPath: "/additional-istio-config"
          name: additional-config
          readOnly: true
        - mountPath: "/istiod-cert"
          name: apigee-istiod-cert
          readOnly: true
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/apigee-release/hybrid/apigee-kube-rbac-proxy:v0.11.0
        imagePullPolicy: IfNotPresent
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        runAsGroup: 998
        runAsUser: 999
      serviceAccount: apigee-ingressgateway-manager
      serviceAccountName: apigee-ingressgateway-manager
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          medium: Memory
        name: local-certs
      - name: istio-token
        projected:
          defaultMode: 420
          sources:
          - serviceAccountToken:
              expirationSeconds: 43200
              path: istio-token
      - name: cacerts
        secret:
          defaultMode: 420
          optional: true
          secretName: cacerts
      - configMap:
          defaultMode: 420
          name: istio-sidecar-injector
          optional: true
        name: inject
      - configMap:
          defaultMode: 420
          name: apigee-istio-mesh-config
        name: config-volume
      - name: istiod-config
        emptyDir: {}
      - name: apigee-istiod-cert
        secret:
          secretName: apigee-istiod-cert
      - configMap:
          defaultMode: 420
          name: apigee-envoyfilter-1.11
        name: envoyfilter
      - configMap:
          defaultMode: 420
          name: apigee-additional-istio-config
          optional: true
        name: additional-config