apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: apigee-leader-election-role
  namespace: apigee
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: apigee-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  - pods
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - persistentvolumes
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - resourcequotas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - services
  verbs:
  - batch
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  - apps
  - authentication.istio.io
  - autoscaling
  - networking.istio.io
  - security.istio.io
  resources:
  - destinationrules
  - events
  - horizontalpodautoscalers
  - peerauthentications
  - persistentvolumeclaims
  - policies
  - replicasets
  - services
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  - networking.istio.io
  resources:
  - events
  - gateways
  - virtualservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions/status
  verbs:
  - update
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeedatastores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeedatastores/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeedatastores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeedeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeedeployments/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeedeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeeenvironments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeeenvironments/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeeenvironments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeeorganizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeeorganizations/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeeorganizations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeeredis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeeredis/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeeredis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeerouteconfigs
  verbs:
  - get
  - list
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeeroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeeroutes/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeeroutes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeetelemetries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeetelemetries/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeetelemetries/status
  verbs:
  - get
  - list
  - patch
  - update
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - cassandradatareplications
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - cassandradatareplications/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - cassandradatareplications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
  - get
  - list
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  - certificates/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - issuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    apigee.cloud.google.com/platform: apigee
  name: apigee-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: apigee-leader-election-rolebinding
  namespace: apigee
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: apigee-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: apigee
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    apigee.cloud.google.com/platform: apigee
  name: apigee-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apigee-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: apigee
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    apigee.cloud.google.com/platform: apigee
  name: apigee-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apigee-proxy-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: apigee
