apiVersion: apigee.cloud.google.com/v1alpha1
kind: ApigeeDatastore
metadata:
  name: "datastore"
spec:
  components:
    cassandra:
      properties:
        multiRegionSeedHost: <IP_ADDRESS> # To be modified. REQUIRED
      hostNetwork: false # Can be modified. OPTIONAL
      # dnsPolicy: ClusterFirstWithHostNet # Can be modified. OPTIONAL. Uncomment if hostNetwork is true.