# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Ingress TLS cert.
# 
# This Certificate can be used in the cases where you want to use self signed
# tls certs for ingress. A Certificate resource generates a secret (having the
# name specified in `spec.secretName`) which will contain a cert and key pair
# depending on the configuration specified. For more info about Certificate
# resource, refer https://cert-manager.io/docs/concepts/certificate/
#
# The secret thus generated is used within a `route-config` resource. Each
# environment group has it's own `route-config` and thus each environment group
# will usually have it's own Certificate.



# If you would like to provide your own certificate information, comment out the
# cert manager provide certificate below and uncomment the Secret definition below

# apiVersion: v1
# kind: Secret
# metadata:
#   name: "${ORGANIZATION_NAME}-${ENVIRONMENT_GROUP_NAME}"
#   namespace: "${APIGEE_NAMESPACE}"
# type: Opaque
# data:
#   cert: |
#     YOUR_CERT_CHAIN_HERE_BASE64_ENCODED
#   key: |
#     YOUR_PRIVATE_KEY_HERE_BASE64_ENCODED




apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${ORGANIZATION_NAME}-${ENVIRONMENT_GROUP_NAME}"
  namespace: "${APIGEE_NAMESPACE}"
spec:
  secretName: "${ORGANIZATION_NAME}-${ENVIRONMENT_GROUP_NAME}"
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - "${ORGANIZATION_NAME}"
  commonName: "${ENVIRONMENT_GROUP_HOSTNAME}"
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
  dnsNames:
    - "${ENVIRONMENT_GROUP_HOSTNAME}"
  issuerRef:
    name: apigee-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io