apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- target:
    group: cert-manager.io
    version: v1
    kind: Certificate
    name: apigee-root-certificate
  patch: |-
    - op: replace
      path: /spec/secretName
      value: unused-apigee-root-certificate