apiVersion: apigee.cloud.google.com/v1alpha1
kind: ApigeeDatastore
metadata:
  name: "datastore"
spec:
  components:
    cassandra:
      containers:
      - name: "apigee-cassandra"
        env:
        - name: APIGEE_CLOUDPROVIDER
          value: "GCP"            
        - name: DBSTORAGE_BUCKET
          value: "<CLOUD_STORAGE_BUCKET_PATH>" # To be modified. REQUIRED
        - name: CASSANDRA_DB_USER
          valueFrom:
            secretKeyRef:
              name: apigee-datastore-default-creds
              key: admin.user
        - name: CASSANDRA_DB_PASS
          valueFrom:
            secretKeyRef:
              name: apigee-datastore-default-creds
              key: admin.password
        volumeMounts:
        - name: apigee-cassandra-restore
          mountPath: /var/secrets/google
      volumes:
      - name: apigee-cassandra-restore
        secret:
          secretName: "apigee-cassandra-backup-and-restore-svc-account"

