apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigee-istiod
spec:
  template:
    spec:
      containers:
      - name: discovery
        env:
        - name: ISTIOD_ADDR
          value: apigee-istiod.apigee.svc:15012 # kpt-set: apigee-istiod.${APIGEE_NAMESPACE}.svc:15012