apiVersion: apigee.cloud.google.com/v1alpha2
kind: ApigeeTelemetry
metadata:
  name: "telemetry"
spec:
  httpForwardProxy:
    scheme: <HTTP|HTTPS> # To be modified. REQUIRED
    host: <HOST> # To be modified. REQUIRED
    port: <PORT> # To be modified. REQUIRED
    username: <USERNAME> # Can be modified. OPTIONAL
    password: <PASSWORD> # Can be modified. OPTIONAL