apiVersion: apigee.cloud.google.com/v1alpha2
kind: ApigeeTelemetry
metadata:
  name: "telemetry"
spec:
  components:
    containerLogs:
      podServiceAccountName: "apigee-containerLogs-workload-identity"