apiVersion: apigee.cloud.google.com/v1alpha2
kind: ApigeeTelemetry
metadata:
  name: "telemetry"
spec:
  components:
    metricsApp:
      nodeAffinityRequired: true
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: cloud.google.com/gke-nodepool
                  operator: In
                  values:
                    - apigee-runtime
    metricsProxy:
      nodeAffinityRequired: true
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: cloud.google.com/gke-nodepool
                  operator: In
                  values:
                    - apigee-runtime
    metricsAdapter:
      nodeAffinityRequired: true
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: cloud.google.com/gke-nodepool
                  operator: In
                  values:
                    - apigee-runtime
    containerLogs:
      nodeAffinityRequired: true
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: cloud.google.com/gke-nodepool
                  operator: In
                  values:
                    - apigee-runtime