apiVersion: apigee.cloud.google.com/v1alpha1
kind: ApigeeDatastore
metadata:
  name: "datastore"
spec:
  components:
    cassandra:
      containers:
      - name: "apigee-cassandra"
        env:
        - name: APIGEE_CLOUDPROVIDER
          value: "HYBRID"
        - name: BACKUP_SERVER_IP
          value: "<BACKUP_SERVER_IP>" # To be modified. REQUIRED
        - name: BACKUP_STORAGE_DIR
          value: "<PATH/TO/DIRECTORY>" # To be modified. REQUIRED
        - name: BACKUP_KEY_FILE
          value: "/var/secrets/keys/key"
        volumeMounts:
        - name: apigee-cassandra-backup-key-file
          mountPath: /var/secrets/keys
      volumes:
      - name: apigee-cassandra-backup-key-file
        secret:
          secretName: apigee-cassandra-backup-and-restore-key-file

