apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- apigee-workload-identities.yaml

patches:
- path: patch.yaml
  target:
    group: apigee.cloud.google.com
    version: v1alpha1
    kind: ApigeeRedis