kind: ApigeeTelemetry
apiVersion: apigee.cloud.google.com/v1alpha2
metadata:
  name: apigee-telemetry
  namespace: "apigee" # kpt-set: ${APIGEE_NAMESPACE}
  labels:
    apigee.cloud.google.com/platform: apigee
spec:
  clusterName: "${CLUSTER_NAME}" # kpt-set: ${CLUSTER_NAME}
  clusterRegion: "${CLUSTER_REGION}" # kpt-set: ${CLUSTER_REGION}
  gcpProjectID: "${GCP_PROJECT_ID}" # kpt-set: ${GCP_PROJECT_ID}