apiVersion: apigee.cloud.google.com/v1alpha2
kind: ApigeeTelemetry
metadata:
  name: "telemetry"
spec:
  components:
    metricsApp:
      podServiceAccountName: "apigee-metrics-app-svc-account"
    metricsProxy:
      podServiceAccountName: "apigee-metrics-proxy-svc-account"
    metricsAdapter:
      podServiceAccountName: "apigee-metrics-adapter-svc-account"