apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: apigee-all-sa@${ORGANIZATION_NAME}.iam.gserviceaccount.com # kpt-set: ${GCP_SERVICE_ACCOUNT_NAME}@${ORGANIZATION_NAME}.iam.gserviceaccount.com
  labels:
    apigee.cloud.google.com/platform: apigee
  name: "apigee-metrics-app-svc-account"
  namespace: apigee # kpt-set: ${APIGEE_NAMESPACE}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: apigee-all-sa@${ORGANIZATION_NAME}.iam.gserviceaccount.com # kpt-set: ${GCP_SERVICE_ACCOUNT_NAME}@${ORGANIZATION_NAME}.iam.gserviceaccount.com
  labels:
    apigee.cloud.google.com/platform: apigee
  name: "apigee-metrics-proxy-svc-account"
  namespace: apigee # kpt-set: ${APIGEE_NAMESPACE}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: apigee-all-sa@${ORGANIZATION_NAME}.iam.gserviceaccount.com # kpt-set: ${GCP_SERVICE_ACCOUNT_NAME}@${ORGANIZATION_NAME}.iam.gserviceaccount.com
  labels:
    apigee.cloud.google.com/platform: apigee
  name: "apigee-metrics-adapter-svc-account"
  namespace: apigee # kpt-set: ${APIGEE_NAMESPACE}
---