apiVersion: apigee.cloud.google.com/v1alpha1
kind: ApigeeRedis
metadata:
  name: "redis"
spec:
  components:
    redis:
      nodeAffinityRequired: true
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: cloud.google.com/gke-nodepool
                  operator: In
                  values:
                    - apigee-runtime
    redisEnvoy:
      nodeAffinityRequired: true
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: cloud.google.com/gke-nodepool
                  operator: In
                  values:
                    - apigee-runtime