apiVersion: apigee.cloud.google.com/v1alpha1
kind: ApigeeRedis
metadata:
  name: default
  namespace: "apigee" # kpt-set: ${APIGEE_NAMESPACE}
  labels:
    apigee.cloud.google.com/platform: apigee
spec:
  name: default
  credentialRef: "apigee-redis-default-creds"

