apiVersion: apigee.cloud.google.com/v1alpha1
kind: ApigeeDatastore
metadata:
  name: default
  namespace: "apigee" # kpt-set: ${APIGEE_NAMESPACE}
  labels:
    apigee.cloud.google.com/platform: apigee
spec:
  credentialRef: "apigee-datastore-default-creds"
  components:
    cassandra:
      storage:
        storageSize: 10Gi
