apiVersion: v1
kind: Secret
metadata:
  name: "org-ax-salt" # kpt-set: ${ORGANIZATION_NAME}-ax-salt
  namespace: "apigee" # kpt-set: ${APIGEE_NAMESPACE}
type: Opaque
data:
  salt: |
    aWxvdmVhcGlzMTIz
---
apiVersion: v1
kind: Secret
metadata:
  name: "org-data-encryption" # kpt-set: ${ORGANIZATION_NAME}-data-encryption
  namespace: "apigee" # kpt-set: ${APIGEE_NAMESPACE}
type: Opaque
data:
  plainTextDEK: aWxvdmVhcGlzMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM=
---
apiVersion: v1
kind: Secret
metadata:
  name: "org-encryption-keys" # kpt-set: ${ORGANIZATION_NAME}-encryption-keys
  namespace: "apigee" # kpt-set: ${APIGEE_NAMESPACE}
type: Opaque
data:
  kmsEncryptionKey: |
    YVd4dmRtVmhjR2x6TVRJek5EVTJOdz09
---