# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Service
metadata:
  labels:
    apigee.cloud.google.com/platform: apigee
    control-plane: controller-manager
  name: apigee-controller-manager-metrics-service
  namespace: "apigee"
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
---
apiVersion: v1
kind: Service
metadata:
  labels:
    apigee.cloud.google.com/platform: apigee
  name: apigee-webhook-service
  namespace: "apigee"
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    apigee.cloud.google.com/platform: apigee
    control-plane: controller-manager
  name: apigee-controller-manager
  namespace: "apigee"
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        apigee.cloud.google.com/platform: apigee
        app: apigee-controller
        control-plane: controller-manager
        revision: "170rc1"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsGroup: 998
        runAsUser: 999
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/apigee-release/hybrid/apigee-kube-rbac-proxy:v0.11.0
        imagePullPolicy: IfNotPresent
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        - --apigee-runtime-type=hybrid
        - --log-level=info
        - --enable-webhooks=true
        - --enable-controllers=true
        - --disable-embedded-asm-apigee-route-controller=true
        - --disable-embedded-asm-apigee-deployment-controller=true
        - --enable-api-client=true
        - --disable-istio-config-in-apiserver=true
        - --disable-common-config-controller=false
        - --disable-control-plane-validation=false
        command:
        - /manager
        image: gcr.io/apigee-release/hybrid/apigee-operators:1.8.0-preview.2
        imagePullPolicy: Always
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        - containerPort: 8081
          name: healthcheck
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /readyz
            port: healthcheck
            scheme: HTTP
          periodSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        - name: tmpfs
          mountPath: /tmp
      terminationGracePeriodSeconds: 10
      volumes:
      - name: tmpfs
        emptyDir: {}
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
---