
# Ingress TLS cert.
# 
# This Certificate can be used in the cases where you want to use self signed
# tls certs for ingress. A Certificate resource generates a secret (having the
# name specified in `spec.secretName`) which will contain a cert and key pair
# depending on the configuration specified. For more info about Certificate
# resource, refer https://cert-manager.io/docs/concepts/certificate/
#
# The secret thus generated is used within a `route-config` resource. Each
# environment group has it's own `route-config` and thus each environment group
# will usually have it's own Certificate.
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${ORGANIZATION_NAME}-${ENVIRONMENT_GROUP_NAME}"
  namespace: "${APIGEE_NAMESPACE}"
spec:
  secretName: "${ORGANIZATION_NAME}-${ENVIRONMENT_GROUP_NAME}"
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - "${ORGANIZATION_NAME}"
  commonName: "${HOSTNAME}"
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
  dnsNames:
    - "${HOSTNAME}"
  issuerRef:
    name: apigee-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io