# Secret containing ingress TLS cert/key pair
#
# Background: Each environment group has a `route-config` resource. This
# `route-config` configures the ingress routing for `apigee-environment`s
# belonging to that environment group. The `route-config` resource references a
# secret which should contain a cert/key pair which will then be used for
# ingress TLS communication. 
#
# Make sure that the cert/key pair corresponds to the hostnames used within the
# environment group.
#
# Refer the comment in `ingress-certificate.yaml` for some additional insight.
apiVersion: v1
kind: Secret
metadata:
  name: "${ORGANIZATION_NAME}-${ENVIRONMENT_GROUP_NAME}"
  namespace: istio-system
type: Opaque
data:
  cert: |
    ${YOUR_CERT_CHAIN_HERE_BASE64_ENCODED}
  key: |
    ${YOUR_PRIVATE_KEY_HERE_BASE64_ENCODED}