# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Usage: Create this secret before performing any GCS backup and restore
# operations for Cassandra
# 
# This secret is only used in GCS backup and restore. It is the service account
# which has the Storage Object Admin permissions to store and retrieve data from
# GCS.
apiVersion: v1
kind: Secret
metadata:
  name: apigee-cassandra-gcp-sa-key
  namespace: "${APIGEE_NAMESPACE}"
type: Opaque
data:
  client_secret.json: |
    ${BASE64_ENCODED_SA_KEYS}

