# Usage: Create this secret before performing any GCS backup and restore
# operations for Cassandra
# 
# This secret is only used in GCS backup and restore. It is the service account
# which has the Storage Object Admin permissions to store and retrieve data from
# GCS.
apiVersion: v1
kind: Secret
metadata:
  name: apigee-cassandra-backup-and-restore-gcp-sa-key
  namespace: "${APIGEE_NAMESPACE}"
type: Opaque
data:
  dbbackup_key.json: |
    ${BASE64_ENCODED_SA_KEYS}

