# Usage: Create this secret before performing any "Non" GCS backup and restore
# operations for Cassandra.
# 
# This secret is supposed to contain the SSH private keys that are required to
# ssh into the server where backup data will be stored. While generating the 
# keys, make sure that the private key is not password protected.
#
# NOTE: Make sure the SSH Private key ends in a newline before base64 encoding
# it.
apiVersion: v1
kind: Secret
metadata:
  name: apigee-cassandra-backup-and-restore-key-file
  namespace: "${APIGEE_NAMESPACE}"
type: Opaque
data:
  "key" : |
    ${BASE64_ENCODED_SSH_PRIVATE_KEY}