# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Usage: Create this secret before performing any "Non" GCS backup and restore
# operations for Cassandra.
# 
# This secret is supposed to contain the SSH private keys that are required to
# ssh into the server where backup data will be stored. While generating the 
# keys, make sure that the private key is not password protected.
#
# NOTE: Make sure the SSH Private key ends in a newline before base64 encoding
# it.
apiVersion: v1
kind: Secret
metadata:
  name: apigee-cassandra-backup-and-restore-key-file
  namespace: "${APIGEE_NAMESPACE}"
type: Opaque
data:
  "key" : |
    ${BASE64_ENCODED_SSH_PRIVATE_KEY}