# Secret containing GCP service account keys
#
# Apigee components will be making API calls to the Apigee Control Plan.
# Authentication for these APIs can be done by using any of the following:
# - Service account keys
# - Workload identity.
#
# For using service account keys, you need to:
# 1. Create the GCP service accounts in your project
# 2. Download the service account keys
# 3. Create kubernetes secrets containing the service account keys.
#
# The below secret represents what those secrets should look like.
apiVersion: v1
kind: Secret
metadata:
  name: "${SA_KEY_SECRET_NAME}"
  namespace: "${APIGEE_NAMESPACE}"
type: Opaque
data:
  client_secret.json: |
    ${BASE64_ENCODED_SA_KEYS}