apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apigee-serving-cert
spec:
  dnsNames:
  - apigee-webhook-service.apigee.svc # kpt-set: apigee-webhook-service.${APIGEE_NAMESPACE}.svc
  - apigee-webhook-service.apigee.svc.cluster.local # kpt-set: apigee-webhook-service.${APIGEE_NAMESPACE}.svc.cluster.local