apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apigee-istiod
spec:
  commonName: apigee-istiod.apigee.svc # kpt-set: apigee-istiod.${APIGEE_NAMESPACE}.svc
  dnsNames:
  - "apigee-istiod.apigee.svc" # kpt-set: apigee-istiod.${APIGEE_NAMESPACE}.svc