namespace: "apigee" # kpt-set: ${APIGEE_NAMESPACE}

resources:
- ../../../bases/initialization/certificates/

patches:
- path: apigee-serving-cert-patch.yaml
  target:
    group: cert-manager.io
    version: v1
    kind: Certificate
    name: apigee-serving-cert
- path: apigee-istiod-certificate-patch.yaml
  target:
    group: cert-manager.io
    version: v1
    kind: Certificate
    name: apigee-istiod