# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

resources:
- ../../../bases/initialization/certificates/

# components:
# - ./components/disable-apigee-root-certificate-generation

patches:
- path: apigee-serving-cert-patch.yaml
  target:
    group: cert-manager.io
    version: v1
    kind: Certificate
    name: apigee-serving-cert
- patch: |- 
    - op: copy
      from: "/metadata/annotations/apigeeNamespace"
      path: /metadata/namespace
  target:
    group: cert-manager.io
    version: v1
    kind: Certificate
    name: apigee-serving-cert

- path: apigee-ingressgateway-manager-certificate-patch.yaml
  target:
    group: cert-manager.io
    version: v1
    kind: Certificate
    name: apigee-istiod
- patch: |- 
    - op: copy
      from: "/metadata/annotations/apigeeNamespace"
      path: /metadata/namespace
  target:
    group: cert-manager.io
    version: v1
    kind: Certificate
    name: apigee-istiod