apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: apigee/apigee-serving-cert
    certmanager.k8s.io/inject-ca-from: apigee/apigee-serving-cert
  name: apigee-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: apigee-webhook-service
      namespace: apigee
      path: /mutate-apigee-cloud-google-com-v1alpha1-apigeedatastore
  failurePolicy: Fail
  name: mapigeedatastore.apigee.cloud.google.com
  rules:
  - apiGroups:
    - apigee.cloud.google.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - apigeedatastores
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: apigee-webhook-service
      namespace: apigee
      path: /mutate-apigee-cloud-google-com-v1alpha2-apigeeenvironment
  failurePolicy: Fail
  name: mapigeeenvironment.apigee.cloud.google.com
  rules:
  - apiGroups:
    - apigee.cloud.google.com
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - apigeeenvironments
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: apigee-webhook-service
      namespace: apigee
      path: /mutate-apigee-cloud-google-com-v1alpha2-apigeeorganization
  failurePolicy: Fail
  name: mapigeeorganization.apigee.cloud.google.com
  rules:
  - apiGroups:
    - apigee.cloud.google.com
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - apigeeorganizations
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: apigee-webhook-service
      namespace: apigee
      path: /mutate-apigee-cloud-google-com-v1alpha1-apigeeredis
  failurePolicy: Fail
  name: mapigeeredis.apigee.cloud.google.com
  rules:
  - apiGroups:
    - apigee.cloud.google.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - apigeeredis
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: apigee-webhook-service
      namespace: apigee
      path: /mutate-apigee-cloud-google-com-v1alpha1-apigeeroute
  failurePolicy: Fail
  name: mapigeeroute.apigee.cloud.google.com
  rules:
  - apiGroups:
    - apigee.cloud.google.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - apigeeroutes
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: apigee-webhook-service
      namespace: apigee
      path: /mutate-apigee-cloud-google-com-v1alpha2-apigeetelemetry
  failurePolicy: Fail
  name: mapigeetelemetry.apigee.cloud.google.com
  rules:
  - apiGroups:
    - apigee.cloud.google.com
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - apigeetelemetrys
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: apigee-webhook-service
      namespace: apigee
      path: /mutate-apigee-cloud-google-com-v1alpha3-apigeedeployment
  failurePolicy: Fail
  name: mapigeedeployment.apigee.cloud.google.com
  rules:
  - apiGroups:
    - apigee.cloud.google.com
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - apigeedeployments
  sideEffects: None

