apiVersion: batch/v1
kind: Job
metadata:
  name: apigee-cassandra-restore
  namespace: apigee
spec:
  template:
    spec:
      # imagePullSecrets:
      # - name: <IMAGE_PULL_SECRET>
      containers:
      - name: apigee-cassandra-restore
        env:
        - name: APIGEE_CLOUDPROVIDER
          value: "HYBRID"
        - name: BACKUP_SNAPSHOT_TIMESTAMP
          value: "TIMESTAMP" # To be modified. REQUIRED
        - name: BACKUP_SERVER_IP
          value: "<BACKUP_SERVER_IP>" # To be modified. REQUIRED
        - name: BACKUP_STORAGE_DIR
          value: "<PATH/TO/DIRECTORY>" # To be modified. REQUIRED
        - name: CASSANDRA_DC
          value: dc-1 # kpt-set: ${CASSANDRA_DC_NAME}
        # - name: http_proxy
        #   value: <HTTP_PROXY_URL>
        volumeMounts:
        - name: apigee-cassandra-restore-key-file
          mountPath: /var/secrets/keys
      securityContext:
        fsGroup: 998
      volumes:
      - name: apigee-cassandra-restore-key-file
        secret:
          secretName: apigee-cassandra-backup-and-restore-key-file