apiVersion: v1
kind: ConfigMap
metadata:
  name: apigee-istio-mesh-config
  namespace: "apigee" # kpt-set: ${APIGEE_NAMESPACE}
  labels:
    apigee.cloud.google.com/platform: apigee
data:
  mesh: |- 
    accessLogEncoding: 1
    accessLogFile: /dev/stdout
    accessLogFormat: '{"start_time":"%START_TIME%","remote_address":"%DOWNSTREAM_DIRECT_REMOTE_ADDRESS%","user_agent":"%REQ(USER-AGENT)%","host":"%REQ(:AUTHORITY)%","request":"%REQ(:METHOD)%
      %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%","request_time":"%DURATION%","status":"%RESPONSE_CODE%","status_details":"%RESPONSE_CODE_DETAILS%","bytes_received":"%BYTES_RECEIVED%","bytes_sent":"%BYTES_SENT%","upstream_address":"%UPSTREAM_HOST%","upstream_response_flags":"%RESPONSE_FLAGS%","upstream_response_time":"%RESPONSE_DURATION%","upstream_service_time":"%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%","upstream_cluster":"%UPSTREAM_CLUSTER%","x_forwarded_for":"%REQ(X-FORWARDED-FOR)%","request_method":"%REQ(:METHOD)%","request_path":"%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%","request_protocol":"%PROTOCOL%","tls_protocol":"%DOWNSTREAM_TLS_VERSION%","request_id":"%REQ(X-REQUEST-ID)%","sni_host":"%REQUESTED_SERVER_NAME%","apigee_dynamic_data":"%DYNAMIC_METADATA(envoy.lua)%"}'
    defaultConfig:
      concurrency: 2
      discoveryAddress: apigee-istiod.apigee.svc:15012 # kpt-set: apigee-istiod.${APIGEE_NAMESPACE}.svc:15012
      drainDuration: 45s
      parentShutdownDuration: 1m0s
      proxyAdminPort: 15000
      serviceCluster: istio-proxy
    disableMixerHttpReports: true
    disablePolicyChecks: true
    enableAutoMtls: false
    enablePrometheusMerge: false
    ingressClass: istio
    ingressControllerMode: DEFAULT
    ingressService: istio-ingressgateway
    localityLbSetting:
      enabled: false
    protocolDetectionTimeout: 0s
    reportBatchMaxEntries: 100
    reportBatchMaxTime: 1s
    sdsUdsPath: unix:/etc/istio/proxy/SDS
    rootNamespace: apigee
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
