resources:
- datastore/
- environments/
- organization/
- redis/
- route-config/
- telemetry/

# TODO(b/218899819): Change version values to a relevant version before the initial release.
patches:
- target:
    group: apigee.cloud.google.com
    version: v1alpha1
    kind: ApigeeDatastore
  patch: |-
    - op: add
      path: /spec/version
      value: 1-6-1
- target:
    group: apigee.cloud.google.com
    version: v1alpha2
    kind: ApigeeEnvironment
  patch: |-
    - op: add
      path: /spec/version
      value: 1-6-1
- target:
    group: apigee.cloud.google.com
    version: v1alpha2
    kind: ApigeeOrganization
  patch: |-
    - op: add
      path: /spec/version
      value: 1-6-1
- target:
    group: apigee.cloud.google.com
    version: v1alpha1
    kind: ApigeeRedis
  patch: |-
    - op: add
      path: /spec/version
      value: 1-6-1
- target:
    group: apigee.cloud.google.com
    version: v1alpha2
    kind: ApigeeTelemetry
  patch: |-
    - op: add
      path: /spec/version
      value: 1-6-1