################################################################################
# Create the root certificate issuer and root certificate
#
# - `apigee-root-certificate-issuer` is used for issuing the root certificates
#   which will inturn be used to issue other certificates
# - `apigee-root-certificate` is the certificate which will be used by other
#   issuers to issue certificates
################################################################################
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: apigee-root-certificate-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apigee-root-certificate
  namespace: cert-manager
spec:
  isCA: true
  duration: 87600h # 10 years
  secretName: apigee-root-certificate
  commonName: apigee-hybrid
  privateKey:
    algorithm: ECDSA
    size: 256
  subject:
    organizations:
    - cluster.local
    - cert-manager
  issuerRef:
    name: apigee-root-certificate-issuer # Uses apigee-root-certificate-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---

################################################################################
# `apigee-ca-issuer` is the issuer which will be used to issue certificates
# for Webhooks, CRDs and individual pods
################################################################################
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: apigee-ca-issuer
spec:
  ca:
    secretName: apigee-root-certificate
---

################################################################################
# `apigee-serving-cert` is used within the Webhooks and CRDs
################################################################################
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: apigee-serving-cert
  namespace: "apigee" # kpt-set: ${APIGEE_NAMESPACE}
spec:
  dnsNames:
  - apigee-webhook-service.apigee.svc
  - apigee-webhook-service.apigee.svc.cluster.local
  issuerRef:
    name: apigee-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  secretName: webhook-server-cert
---

################################################################################
# `apigee-istiod` is used for communication b/w istiod and ingress
################################################################################
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apigee-istiod
  namespace: "apigee" # kpt-set: ${APIGEE_NAMESPACE}
  labels:
    apigee.cloud.google.com/platform: apigee
spec:
  commonName: istiod.apigee.svc # kpt-set: istiod.${APIGEE_NAMESPACE}.svc
  dnsNames:
  - "istiod.apigee.svc" # kpt-set: istiod.${APIGEE_NAMESPACE}.svc
  duration: 17520h0m0s # 2 year.
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    # TODO(b/216376860): Use apigee-ca-issuer to as issuer.
    name: apigee-root-certificate-issuer
  renewBefore: 8760h0m0s # 1 year.
  secretName: apigee-istiod-cert
