apiVersion: apigee.cloud.google.com/v1alpha1
kind: ApigeeDatastore
metadata:
  name: "datastore"
spec:
  components:
    cassandra:
      containers:
      - name: "apigee-cassandra"
        env:
        - name: APIGEE_CLOUDPROVIDER
          value: "GCP"            
        - name: DBSTORAGE_BUCKET
          value: "<CLOUD_STORAGE_BUCKET_PATH>" # To be modified. REQUIRED
        volumeMounts:
        - name: apigee-cassandra-backup
          mountPath: /var/secrets/google
      volumes:
      - name: apigee-cassandra-backup
        secret:
          secretName: "apigee-cassandra-backup-and-restore-svc-account"

